version: "3.8"
services:
  redis:
    build:
      context: .
      dockerfile: dockerfile.redis
    container_name: redis
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 200M

  api:
    build:
      context: ./coaster-api
      dockerfile: dockerfile
    container_name: coaster-api
    ports:
      - "3000:3000"
    depends_on:
      - redis
